### ISSUE TITLE
Is this as dangerous as it looks on first glance?

### ISSUE THREAD

**Issue by spullara** [redplanetlabs/rama-demo-gallery#1]
Won't this be a [# of buckets] recursive call or am I reading it wrong?

https://github.com/redplanetlabs/rama-demo-gallery/blob/7f13e9b255b940fd301ff911e9bc30067f2478c8/src/main/java/rama/gallery/timeseries/TimeSeriesModule.java#L101

**Comment by nathanmarz** [comment]
That recurses by the number of granularities, of which there are only four (minute, hour, day, thirty-day). The function determines what range of buckets to read from each granularity to minimize the work for the query.
